theme: jekyll-theme-minimal
title: Simon
description: Historic articles, documentation, and technical data for Simon, the first Smartphone
logo: /Promotional_materials/IMG copy.jpg
google_analytics: G-9S0GYBKCGT
